In [14]:
#pip install citipy

## Dependencies

In [15]:
import pandas as pd
from sqlalchemy import create_engine
import datetime as dt
import json
import requests
import time
import urllib
#from api_keys import weather_api_key
#from citipy import citipy
import matplotlib.pyplot as plt

### Store CSV into DataFrame

In [16]:
# Import citibike CSV file and Read it (Jan-Jun, 2019)


citibike1901_csv = pd.read_csv('201901-citibike-tripdata.csv')
citibike1902_csv = pd.read_csv('201902-citibike-tripdata.csv')
citibike1903_csv = pd.read_csv('201903-citibike-tripdata.csv')
citibike1904_csv = pd.read_csv('201904-citibike-tripdata.csv')
citibike1905_csv = pd.read_csv('201905-citibike-tripdata.csv')
citibike1906_csv = pd.read_csv('201906-citibike-tripdata.csv')
citibike1907_csv = pd.read_csv('201907-citibike-tripdata.csv')
citibike1908_csv = pd.read_csv('201908-citibike-tripdata.csv')
citibike1909_csv = pd.read_csv('201909-citibike-tripdata.csv')
citibike1910_csv = pd.read_csv('201910-citibike-tripdata.csv')
citibike1911_csv = pd.read_csv('201911-citibike-tripdata.csv')
citibike1912_csv = pd.read_csv('201912-citibike-tripdata.csv')

combined_df = pd.concat([citibike1901_csv, citibike1902_csv, citibike1903_csv,citibike1904_csv, citibike1905_csv, 
                         citibike1906_csv, citibike1907_csv, citibike1908_csv, citibike1909_csv, citibike1910_csv, 
                         citibike1911_csv, citibike1912_csv])

combined_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,320,1/1/19 12:01 AM,1/1/19 12:07 AM,3160,Central Park West & W 76 St,40.778968,-73.973747,3283,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,male
1,316,1/1/19 12:04 AM,1/1/19 12:10 AM,519,Pershing Square North,40.751873,-73.977706,518,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,male
2,591,1/1/19 12:06 AM,1/1/19 12:15 AM,3171,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,male
3,2719,1/1/19 12:07 AM,1/1/19 12:52 AM,504,1 Ave & E 16 St,40.732219,-73.981656,3709,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,male
4,303,1/1/19 12:07 AM,1/1/19 12:12 AM,229,Great Jones St,40.727434,-73.993790,503,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,844,12/1/19 12:13 AM,12/1/19 12:27 AM,453,W 22 St & 8 Ave,40.744751,-73.999154,494,W 26 St & 8 Ave,40.747348,-73.997236,16397,Customer,1998,male
95,147,12/1/19 12:13 AM,12/1/19 12:15 AM,3373,3 St & 3 Ave,40.675071,-73.987752,3368,5 Ave & 3 St,40.672816,-73.983524,28714,Subscriber,1961,female
96,467,12/1/19 12:13 AM,12/1/19 12:21 AM,402,Broadway & E 22 St,40.740343,-73.989551,509,9 Ave & W 22 St,40.745497,-74.001971,38555,Subscriber,1987,female
97,1995,12/1/19 12:13 AM,12/1/19 12:47 AM,533,Broadway & W 38 St,40.752996,-73.987216,3499,2 Ave & E 122 St,40.800672,-73.934900,40335,Subscriber,1996,female
98,605,12/1/19 12:13 AM,12/1/19 12:24 AM,3175,W 70 St & Amsterdam Ave,40.777480,-73.982886,533,Broadway & W 38 St,40.752996,-73.987216,33867,Subscriber,1984,male

## Clean CSV data

In [17]:
# Clean the CSV DF Column headers
citibike_2019 = combined_df.rename(columns = {'tripduration':'Trip Duration', 'starttime':'Start Time', 
                                                'stoptime':'Stop Time','start station id':'Start Station ID',
                                                'start station name':'Start Station Name', 'start station latitude':'Start Station Latitude', 
                                                'start station longitude':'Start Station Longitude','end station id':'End Station ID',
                                                'end station name':'End Station Name','end station latitude':'End Station Latitude', 
                                                'end station longitude':'End Station Longitude','bikeid':'Bike ID','usertype':'User Type',
                                                'birth year':'Birth Year', 'gender': 'Gender'})
citibike_2019

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,320,1/1/19 12:01 AM,1/1/19 12:07 AM,3160,Central Park West & W 76 St,40.778968,-73.973747,3283,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,male
1,316,1/1/19 12:04 AM,1/1/19 12:10 AM,519,Pershing Square North,40.751873,-73.977706,518,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,male
2,591,1/1/19 12:06 AM,1/1/19 12:15 AM,3171,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,male
3,2719,1/1/19 12:07 AM,1/1/19 12:52 AM,504,1 Ave & E 16 St,40.732219,-73.981656,3709,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,male
4,303,1/1/19 12:07 AM,1/1/19 12:12 AM,229,Great Jones St,40.727434,-73.993790,503,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,844,12/1/19 12:13 AM,12/1/19 12:27 AM,453,W 22 St & 8 Ave,40.744751,-73.999154,494,W 26 St & 8 Ave,40.747348,-73.997236,16397,Customer,1998,male
95,147,12/1/19 12:13 AM,12/1/19 12:15 AM,3373,3 St & 3 Ave,40.675071,-73.987752,3368,5 Ave & 3 St,40.672816,-73.983524,28714,Subscriber,1961,female
96,467,12/1/19 12:13 AM,12/1/19 12:21 AM,402,Broadway & E 22 St,40.740343,-73.989551,509,9 Ave & W 22 St,40.745497,-74.001971,38555,Subscriber,1987,female
97,1995,12/1/19 12:13 AM,12/1/19 12:47 AM,533,Broadway & W 38 St,40.752996,-73.987216,3499,2 Ave & E 122 St,40.800672,-73.934900,40335,Subscriber,1996,female
98,605,12/1/19 12:13 AM,12/1/19 12:24 AM,3175,W 70 St & Amsterdam Ave,40.777480,-73.982886,533,Broadway & W 38 St,40.752996,-73.987216,33867,Subscriber,1984,male

In [18]:
# Fix the date and time columns
citibike_2019['Start Date']=pd.to_datetime(citibike_2019['Start Time']).dt.strftime('%Y-%m-%d') #.date
citibike_2019['Start Time']=pd.to_datetime(citibike_2019['Start Time']).dt.strftime('%H:%M') #.dt.time
citibike_2019['Stop Date']=pd.to_datetime(citibike_2019['Stop Time']).dt.strftime('%Y-%m-%d') #.date
citibike_2019['Stop Time']=pd.to_datetime(citibike_2019['Stop Time']).dt.strftime('%H:%M') #.dt.time
citibike_2019

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender,Start Date,Stop Date
0,320,00:01,00:07,3160,Central Park West & W 76 St,40.778968,-73.973747,3283,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,male,2019-01-01,2019-01-01
1,316,00:04,00:10,519,Pershing Square North,40.751873,-73.977706,518,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,male,2019-01-01,2019-01-01
2,591,00:06,00:15,3171,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,male,2019-01-01,2019-01-01
3,2719,00:07,00:52,504,1 Ave & E 16 St,40.732219,-73.981656,3709,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,male,2019-01-01,2019-01-01
4,303,00:07,00:12,229,Great Jones St,40.727434,-73.993790,503,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,male,2019-01-01,2019-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,844,00:13,00:27,453,W 22 St & 8 Ave,40.744751,-73.999154,494,W 26 St & 8 Ave,40.747348,-73.997236,16397,Customer,1998,male,2019-12-01,2019-12-01
95,147,00:13,00:15,3373,3 St & 3 Ave,40.675071,-73.987752,3368,5 Ave & 3 St,40.672816,-73.983524,28714,Subscriber,1961,female,2019-12-01,2019-12-01
96,467,00:13,00:21,402,Broadway & E 22 St,40.740343,-73.989551,509,9 Ave & W 22 St,40.745497,-74.001971,38555,Subscriber,1987,female,2019-12-01,2019-12-01
97,1995,00:13,00:47,533,Broadway & W 38 St,40.752996,-73.987216,3499,2 Ave & E 122 St,40.800672,-73.934900,40335,Subscriber,1996,female,2019-12-01,2019-12-01
98,605,00:13,00:24,3175,W 70 St & Amsterdam Ave,40.777480,-73.982886,533,Broadway & W 38 St,40.752996,-73.987216,33867,Subscriber,1984,male,2019-12-01,2019-12-01

In [19]:
citibike_2019.to_csv('citibike_2019.csv')
print (citibike_2019)

    Trip Duration Start Time Stop Time  Start Station ID  \
0             320      00:01     00:07              3160
1             316      00:04     00:10               519
2             591      00:06     00:15              3171
3            2719      00:07     00:52               504
4             303      00:07     00:12               229
..            ...        ...       ...               ...
94            844      00:13     00:27               453
95            147      00:13     00:15              3373
96            467      00:13     00:21               402
97           1995      00:13     00:47               533
98            605      00:13     00:24              3175

             Start Station Name  Start Station Latitude  \
0   Central Park West & W 76 St               40.778968
1         Pershing Square North               40.751873
2       Amsterdam Ave & W 82 St               40.785247
3               1 Ave & E 16 St               40.732219
4                Great Jones St               40.727434
..                          ...                     ...
94              W 22 St & 8 Ave               40.744751
95                 3 St & 3 Ave               40.675071
96           Broadway & E 22 St               40.740343
97           Broadway & W 38 St               40.752996
98      W 70 St & Amsterdam Ave               40.777480

    Start Station Longitude  End Station ID        End Station Name  \
0                -73.973747            3283  W 89 St & Columbus Ave
1                -73.977706             518         E 39 St & 2 Ave
2                -73.976673            3154         E 77 St & 3 Ave
3                -73.981656            3709         W 15 St & 6 Ave
4                -73.993790             503      E 20 St & Park Ave
..                      ...             ...                     ...
94               -73.999154             494         W 26 St & 8 Ave
95               -73.987752            3368            5 Ave & 3 St
96               -73.989551             509         9 Ave & W 22 St
97               -73.987216            3499        2 Ave & E 122 St
98               -73.982886             533      Broadway & W 38 St

    End Station Latitude  End Station Longitude  Bike ID   User Type  \
0              40.788221             -73.970416    15839  Subscriber
1              40.747804             -73.973442    32723  Subscriber
2              40.773142             -73.958562    27451  Subscriber
3              40.738046             -73.996430    21579  Subscriber
4              40.738274             -73.987520    35379  Subscriber
..                   ...                    ...      ...         ...
94             40.747348             -73.997236    16397    Customer
95             40.672816             -73.983524    28714  Subscriber
96             40.745497             -74.001971    38555  Subscriber
97             40.800672             -73.934900    40335  Subscriber
98             40.752996             -73.987216    33867  Subscriber

    Birth Year  Gender  Start Date   Stop Date
0         1971    male  2019-01-01  2019-01-01
1         1964    male  2019-01-01  2019-01-01
2         1987    male  2019-01-01  2019-01-01
3         1990    male  2019-01-01  2019-01-01
4         1979    male  2019-01-01  2019-01-01
..         ...     ...         ...         ...
94        1998    male  2019-12-01  2019-12-01
95        1961  female  2019-12-01  2019-12-01
96        1987  female  2019-12-01  2019-12-01
97        1996  female  2019-12-01  2019-12-01
98        1984    male  2019-12-01  2019-12-01

[1188 rows x 17 columns]